---
# tasks file for apache
- name: install apache
  yum: name=httpd-devel
  become: yes
  become_method: sudo

- name: pip install mod_wsgi
  pip: name=mod_wsgi
  become: yes
  become_method: sudo

- name: start apache
  service: name=httpd state=started enabled=yes
  become: yes
  become_method: sudo

- name: disable apache trace
  lineinfile: dest=/etc/httpd/conf/httpd.conf state=present line="TraceEnable off"
  become: yes
  become_method: sudo
    
